version: "3.8"
services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

  mongosh:
    image: mongo
    depends_on:
      - mongodb
    entrypoint: ["mongosh", "mongodb://mongodb:27017"]
    stdin_open: true
    tty: true

  server:
    build: server
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  client:
    build: client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  data:
